version: "3"

services:
  app:
    build:
      context: .
      dockerfile: ./docker_files/Dockerfile
    volumes:
      - .:/usr/src/security_notification_bot
      - app_poetry:/root/.cache/pypoetry
    tty: true
    environment:
      PYTHONPATH: /usr/src/security_notification_bot/security_notification_bot
      PYTHONDONTWRITEBYTECODE: 1
    command: bash -c "poetry install; /bin/bash"

  db:
    image: postgres:14.6
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_INITDB_ARGS: "-E UTF8"
      TZ: "Asia/Tokyo"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db:/tmp/db
    ports:
      - 5432:5432

volumes:
  app_poetry:
    external: false
  db_data:
    external: false
