version: "3"

services:
  app:
    build:
      context: .
      dockerfile: ./docker_files/Dockerfile
    volumes:
      - .:/usr/src/greedy_collectorv
      - app_poetry:/root/.cache/pypoetry
    tty: true
    environment:
      PYTHONPATH: /usr/src/greedy_collector/greedy_collector
      PYTHONDONTWRITEBYTECODE: 1
    command: bash -c "poetry install; /bin/bash"

volumes:
  app_poetry:
    external: false
